import { registerSW } from 'virtual:pwa-register'

/**
 * Register the service worker generated by vite-plugin-pwa.
 * `autoUpdate` mode is configured in vite.config, so new versions are
 * fetched silently and activated on the next navigation.
 */
export function registerServiceWorker(): void {
  if (typeof window === 'undefined' || !('serviceWorker' in navigator)) return

  const updateSW = registerSW({
    immediate: true,
    onRegisterError(err) {
      console.warn('[pwa] service worker failed to register', err)
    },
  })

  // Re-export the update function on window for future manual refresh UI.
  ;(window as Window & { __gtunerUpdateSW?: typeof updateSW }).__gtunerUpdateSW = updateSW
}
